include_guard(GLOBAL)

function(cunqa_detect_platform)
  set(_system_name "$ENV{LMOD_SYSTEM_NAME}")
  if(NOT _system_name OR NOT (_system_name STREQUAL "QMIO" OR _system_name STREQUAL "FT3"))
    set(_system_name "EXTERNAL_CLUSTER")
  endif()
  set(SYSTEM_NAME "${_system_name}" PARENT_SCOPE)
endfunction()

function(cunqa_configure_python_and_pybind11)
  if(SYSTEM_NAME STREQUAL "QMIO")
    set(pybind11_DIR "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/pybind11/2.13.6-python-3.11.9/lib64/python3.11/site-packages/pybind11/share/cmake/pybind11/")
    find_package(Python 3.11.9 COMPONENTS Interpreter Development)
    find_package(pybind11 2.13 REQUIRED)
    set(pybind11_FOUND "${pybind11_FOUND}" PARENT_SCOPE)
    set(Python_INCLUDE_DIRS "${Python_INCLUDE_DIRS}" PARENT_SCOPE)
    set(Python_LIBRARIES "${Python_LIBRARIES}" PARENT_SCOPE)
  elseif(SYSTEM_NAME STREQUAL "FT3")
    set(pybind11_DIR "/opt/cesga/2020/software/Core/pybind11/2.13.1-python-3.9.9/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/")
    include_directories("/opt/cesga/2020/software/Core/python/3.9.9/include/python3.9/")
    find_package(Python 3.9.9 EXACT COMPONENTS Interpreter Development)
    find_package(pybind11 2.13.1 REQUIRED)
    set(pybind11_FOUND "${pybind11_FOUND}" PARENT_SCOPE)
    set(Python_INCLUDE_DIRS "${Python_INCLUDE_DIRS}" PARENT_SCOPE)
  else()
    find_package(Python 3.9 COMPONENTS Interpreter Development)
    find_package(pybind11 2.7 REQUIRED)
  endif()
endfunction()
