name: Connect to VPN

on:
  push:
    branches: 
      - main
      - 62-testssss-automatic

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
    - name: Obtain snx and configure
      run: |
        wget http://bigdata.cesga.es/files/snx
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install libaudit1:i386 libbsd0:i386 libc6:i386 libcap-ng0:i386 libgcc-s1:i386 libpam0g:i386 libstdc++5:i386 libx11-6:i386 libxau6:i386 libxcb1:i386 libxdmcp6:i386
        sudo apt install -y expect
        chmod +x ./snx
      
    - name: Creating and executing expect file
      run: |
        cat << 'EOF' > snx_login.exp
        #!/usr/bin/expect

        #Spawn:
        spawn sudo ./snx -s secure.cesga.es -u ${{ secrets.USERNAME }}

        #Brief delay to send automatically the password. You don't have to do anything:
        expect "Please enter your password:"
        send "${{ secrets.PASSWD }}\r"

        #It waits for the confirmation and answers "Yes" by default.
        expect "Do you accept? \[y\]es/ \[N\]o:"
        send "y"

        #Ends of expect command
        expect eof
        
        EOF
        ls
        chmod +x snx_login.exp
        sudo ./snx_login.exp

    - name: Create build and test file
      run: |
        cat << 'EOF' > snx_login.exp
        #!/bin/bash

        EOF

    - name: Remote ssh execution 
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.USERNAME }}
        proxy_key: ${{ secrets.KEY }}
        script: |
          echo $LMOD_SYSTEM_NAME
          cd /mnt/netapp1/Store_CESGA/home/cesga/dexposito/repos/CUNQA/cunqa

          # In the next line (LOADING MODULES) &> /dev/null redirects output so terminal isn't clogged (it will be ignored in /dev/null)                    
          module load qmio/hpc gcc/12.3.0 hpcx-ompi flexiblas/3.3.0 boost cmake/3.27.6 pybind11/2.12.0-python-3.9.9 nlohmann_json/3.11.3 ninja/1.9.0 qiskit/1.2.4-python-3.9.9 &> /dev/null

          echo "                  "

          # Run a trivial program on node c7-18 and continue executing (& at the end) to reduce waiting time
          bash /mnt/netapp1/Store_CESGA/home/cesga/dexposito/repos/CUNQA/code_tests/wake_up_c7_18.sh & 

          python /mnt/netapp1/Store_CESGA/home/cesga/dexposito/repos/CUNQA/code_tests/tesst_runner.py
          echo "After LOGIN tests"

          # Start interactive session for all tests that don't use the python qraise command. qcompute would be faster but would take 5mins to power on sleeping nodes
          qcompute -c 60 --node c7-18
          module load qmio/hpc gcc/12.3.0 hpcx-ompi flexiblas/3.3.0 boost cmake/3.27.6 pybind11/2.12.0-python-3.9.9 nlohmann_json/3.11.3 ninja/1.9.0 qiskit/1.2.4-python-3.9.9 &> /dev/null

          echo "                  "
          

          python /mnt/netapp1/Store_CESGA/home/cesga/dexposito/repos/CUNQA/code_tests/tesst_runner_interactive.py

          # Now kill the qinteractive session to free the resources
          scancel $SLURM_JOB_ID 
          echo "After INTERACTIVE tests"




